Added test results workflow
The test results are now displayed on the action page

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -19,28 +19,33 @@ jobs:
   # Set the job key. The key is displayed as the job name
   # when a job name is not provided
   build-and-test:
-    # Name the Job
-    name: Build code base and run tests
+    # Name the job
+    name: Build & Test
     # Set the type of machine to run on
     runs-on: ubuntu-latest
 
     steps:
-      # Checks out a copy of your repository on the ubuntu-latest machine
-      # See: https://github.com/actions/checkout
       - name: Get code
+        # See: https://github.com/actions/checkout
         uses: actions/checkout@v2
         with:
           lfs: true
           submodules: true
 
-      # See: https://github.com/actions/setup-dotnet
+      # This creates ${{ steps.short-sha.outputs.sha }} to be used below.
+      - name: Determine Git short commit hash
+        # See: https://github.com/marketplace/actions/short-sha
+        uses: benjlevesque/short-sha@56c9032868f85fc82058ff0793e58ab97bb2b856
+        id: short-sha
+
       - name: Setup .NET build environment
+        # See: https://github.com/actions/setup-dotnet
         uses: actions/setup-dotnet@v1
         with:
           # NOTE: Apparently only the 3rd component can be "x"; i.e. "5.x" is not supported.
           dotnet-version: '5.0.x'
 
-      - name: Install NuGet dependencies
+      - name: Download NuGet dependencies
         run: dotnet restore
 
       - name: Build main solution
@@ -51,4 +56,16 @@ jobs:
       - name: Run tests
         # See: https://docs.microsoft.com/de-de/dotnet/core/tools/dotnet-test
         # NOTE: Without specifying a solution file, "dotnet test" searches for a .sln file in the current directory.
-        run: RUNS_IN_CI=true dotnet test --configuration Release --no-restore --no-build --nologo
+        # NOTE 2: There seems to be no way to name the .trx file as '<project>.trx'. If no 'LogFileName' is specified,
+        #   the .trx files will be named something like "_fv-az278-737_2021-08-15_03_50_33.trx".
+        run: RUNS_IN_CI=true dotnet test --configuration Release --no-restore --no-build --logger "trx;LogFileName=test-results.trx" --nologo
+
+      - name: Upload test results
+        # See: https://github.com/actions/upload-artifact
+        uses: actions/upload-artifact@v2
+        # run this step even if previous step failed
+        if: success() || failure()
+        with:
+          name: test-results-${{ steps.short-sha.outputs.sha }}
+          path: '**/*.trx'
+          if-no-files-found: error
